Задача 4.
Симметричные пары:
Условие: Дана таблица items (id, name, category).
Задание: Найди все пары записей, у которых полностью совпадают name и category. Пары (id1, id2) и (id2, id1) считай идентичными (оставь только одну). Пары с одинаковыми ID необходимо исключить.
Ожидаемый результат: id1, id2, category.

In [1]:
import pandas as pd

In [2]:
data = {
    'name': ['Товар А', 'Товар Б', 'Товар А', 'Товар А', 'Товар Б'],
    'category': ['Электроника', 'Одежда', 'Электроника', 'Книги', 'Одежда']
}
items = pd.DataFrame(data)
items = items.reset_index().rename(columns={'index': 'id'})

In [3]:
items

   id     name     category
0   0  Товар А  Электроника
1   1  Товар Б       Одежда
2   2  Товар А  Электроника
3   3  Товар А        Книги
4   4  Товар Б       Одежда

In [4]:
merged = pd.merge(items, items, on=['name', 'category'], suffixes=('1', '2'))

In [5]:
merged

   id1     name     category  id2
0    0  Товар А  Электроника    0
1    0  Товар А  Электроника    2
2    1  Товар Б       Одежда    1
3    1  Товар Б       Одежда    4
4    2  Товар А  Электроника    0
5    2  Товар А  Электроника    2
6    3  Товар А        Книги    3
7    4  Товар Б       Одежда    1
8    4  Товар Б       Одежда    4

In [6]:
result = merged[merged['id1'] < merged['id2']] # исключение идентичных пар и записей без пары
result = result[['id1', 'id2', 'category']]
result

   id1  id2     category
1    0    2  Электроника
3    1    4       Одежда